// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVcCI1-F516KyDNtE5j58pZpiW5-dXTc',
    appId: '1:1016790110313:web:bb077c436e5f06bd7cd2f8',
    messagingSenderId: '1016790110313',
    projectId: 'hotelmutu',
    authDomain: 'hotelmutu.firebaseapp.com',
    storageBucket: 'hotelmutu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_7gQvVHsC9JO7sdqluHr2qmreFdTpHPw',
    appId: '1:1016790110313:android:c07340810814b3e77cd2f8',
    messagingSenderId: '1016790110313',
    projectId: 'hotelmutu',
    storageBucket: 'hotelmutu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGP1uwKO5vZUyrCBovg4GGrStCuVcmJi0',
    appId: '1:1016790110313:ios:3cd90cee597f42707cd2f8',
    messagingSenderId: '1016790110313',
    projectId: 'hotelmutu',
    storageBucket: 'hotelmutu.appspot.com',
    iosClientId: '1016790110313-svd3bl49tm2lgbbaokocm11a8m35r0io.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaCozy',
  );
}
